config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :postings do
    resources :post_comments, module: :postings
  end

  root to: "postings#index"

end

app/models/post_comment.rb
# == Schema Information
#
# Table name: post_comments
#
#  id         :integer          not null, primary key
#  posting_id :integer
#  user_id    :integer
#  body       :text
#  avatar     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostComment < ActiveRecord::Base
  belongs_to :postings
  belongs_to :user
  validates :body, presence: true
end

app/models/posting.rb
# == Schema Information
#
# Table name: postings
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  amount     :string
#  tags       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Posting < ActiveRecord::Base
  belongs_to :user
  has_many :post_comments

  accepts_nested_attributes_for :post_comments

  validates :title, presence: true
  validates_associated :post_comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :postings
  has_many :post_comments

  def name
   "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/postings/post_comments_controller.rb
class Postings::PostCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_posting

  def create
    @post_comment = @posting.post_comments.new post_comment_params
    @post_comment.user = current_user

    if @post_comment.save
      redirect_to posting_path(@posting, anchor: "post_comment_#{@post_comment.id}"), notice: "Successfully posted!"
    else
      redirect_to @posting, alert: "Unable to save your post"
    end
  end

private

    def set_posting
      @posting = Posting.find(params[:posting_id])
    end

    def post_comment_params
      params.require(:post_comment).permit(:body, :user_id)
    end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_posting, except: [:index, :new, :create]

  def index
    @postings = Posting.all
  end

  def show
    @posting = Posting.new
  end

  def new
    @posting = Posting.new
    @posting.post_comments.new
    # @posting.post_comments.save
  end

  def create
    @posting = current_user.postings.new posting_params
    @posting.post_comments.first.user_id = current_user.id

    if @posting.save
      redirect_to @posting
    else
      render action: :new
    end
  end

private

    def set_posting
      @posting = Posting.find(params[:id])
    end

    def posting_params
      params.require(:posting).permit(:title, post_comments_attributes: [:body])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LMFTApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/post_comments/_form.html.erb
<%= form_for [@posting, @post_comment] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/post_comments/_post_comments.html.erb
<%= div_for posting do %>
  <p class="text-muted">Posted by <%= posting.user.name %></p>
  <p><%= posting.body %></p>
<% end %>

app/views/postings/_form.html.erb
<%= form_for @posting do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Test Subject", class: "form-control" %>
  </div>

  <%= f.fields_for :post_comments do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: "Test Add a comment", rows: 10, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/postings/_post_comment.html.erb
<hr />
<p class="text-muted">Posted by <%= posting.user.name %></p>
<p><%= posting.body %></p>

app/views/postings/_posting.html.erb
<%= link_to posting do %>
  <h3><%= posting.title %></h3>
<% end %>

app/views/postings/edit.html.erb
<h1>Editing posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to "Create new Listing!", new_posting_path, class: "btn btn-success" %>
  </div>

  <h1 class="page-header">Listings!</h1>
  <%= render @postings %>
</div>

app/views/postings/new.html.erb
<h1>New Listing</h1>

<%= render "form" %>

app/views/postings/show.html.erb
<div class="container">
  <h1><%= @posting.title %></h1>
  <p class="text-muted">Created by <%= @posting.user.name %></p>
  <%= render @posting.post_comments %>

  <hr />
  <%= render partial: "post_comments/form" %>
</div>